# Generated by Django 5.2.12 on 2026-03-07 04:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ポジション名')),
                ('slug', models.SlugField(unique=True, verbose_name='識別スラッグ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'ポジション',
                'verbose_name_plural': 'ポジション',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='例: 大阪公演、稽古、倉庫作業', max_length=100, verbose_name='ブロック名')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': '工程ブロック',
                'verbose_name_plural': '工程ブロック',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工程種別名')),
                ('slug', models.SlugField(unique=True, verbose_name='識別スラッグ')),
                ('color', models.CharField(default='#3182ce', help_text='カラーコード（例: #3182ce）', max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='表示色')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '工程種別',
                'verbose_name_plural': '工程種別',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='実施日')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='場所')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時間')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='productions.process', verbose_name='工程ブロック')),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productions.processtype', verbose_name='工程種別')),
            ],
            options={
                'verbose_name': '工程タスク',
                'verbose_name_plural': '工程タスク',
                'ordering': ['date', 'order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='例: 2026-PROD-001', max_length=50, unique=True, verbose_name='公演コード')),
                ('title', models.CharField(max_length=200, verbose_name='公演タイトル')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_productions', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '公演',
                'verbose_name_plural': '公演',
            },
        ),
        migrations.AddField(
            model_name='process',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='productions.production', verbose_name='公演'),
        ),
        migrations.CreateModel(
            name='VehicleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100, verbose_name='車両名/種別')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='必要台数')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('process_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_requests', to='productions.processday', verbose_name='工程タスク')),
            ],
            options={
                'verbose_name': '車両申請',
                'verbose_name_plural': '車両申請',
            },
        ),
        migrations.CreateModel(
            name='ProductionHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='休演日')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='備考')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='productions.production', verbose_name='公演')),
            ],
            options={
                'verbose_name': '休演日',
                'verbose_name_plural': '休演日',
                'unique_together': {('production', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='必要人数')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productions.position', verbose_name='ポジション')),
                ('process_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_requests', to='productions.processday', verbose_name='工程タスク')),
            ],
            options={
                'verbose_name': '人員申請',
                'verbose_name_plural': '人員申請',
                'unique_together': {('process_day', 'position')},
            },
        ),
    ]
