# Generated by Django 5.2.12 on 2026-03-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_initial_master_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='production',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('production', 'title')},
        ),
        migrations.AddIndex(
            model_name='processday',
            index=models.Index(fields=['date'], name='productions_date_ad8e2b_idx'),
        ),
    ]
