# Generated by Django 5.2.12 on 2026-03-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0003_alter_production_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='processday',
            name='productions_date_ad8e2b_idx',
        ),
        migrations.AddIndex(
            model_name='processday',
            index=models.Index(fields=['process', 'date'], name='productions_process_bd1bad_idx'),
        ),
    ]
