# Generated by Django 5.2.12 on 2026-03-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0004_remove_processday_productions_date_ad8e2b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='category',
            field=models.CharField(choices=[('rehearsal', '稽古場関連'), ('venue', '劇場関連'), ('warehouse', '倉庫関連'), ('logistics', '荷積み荷降ろし・輸送関連'), ('performance', '本番関連'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリー'),
        ),
    ]
