# Generated by Django 5.2.12 on 2026-03-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0005_processtype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='テンプレート名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('template_data', models.JSONField(verbose_name='テンプレートデータ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '工程テンプレート',
                'verbose_name_plural': '工程テンプレート',
                'ordering': ['name'],
            },
        ),
    ]
