# Generated by Django 5.2.12 on 2026-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0012_vehiclerequest_arrival_requested_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffrequest',
            options={'ordering': ['position__order', 'start_time'], 'verbose_name': '人員申請', 'verbose_name_plural': '人員申請'},
        ),
        migrations.AlterUniqueTogether(
            name='staffrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffrequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='staffrequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='vehiclerequest',
            name='request_kind',
            field=models.CharField(choices=[('load_in', '搬入'), ('pickup', '引き取り'), ('loading', '荷積み'), ('preload', '積み置き'), ('unloading', '荷降ろし'), ('other', 'その他')], default='load_in', max_length=20, verbose_name='申請種別'),
        ),
    ]
