# Generated by Django 5.2.12 on 2026-03-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0013_vehicleoperation_requested_staff_count'),
        ('productions', '0013_alter_staffrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '未対応'), ('reviewing', '調整中'), ('confirmed', '確定')], default='pending', max_length=20, verbose_name='管理状態')),
                ('note', models.TextField(blank=True, default='', verbose_name='管理メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_vehicle_assignments', to='performances.vehicle', verbose_name='手配車両')),
                ('vehicle_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='productions.vehiclerequest', verbose_name='車両申請')),
            ],
            options={
                'verbose_name': '車両手配',
                'verbose_name_plural': '車両手配一覧',
                'ordering': ['vehicle_request__process_day__date', 'vehicle_request__requested_time'],
            },
        ),
    ]
