# Generated by Django 5.2.12 on 2026-03-09 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0014_vehicleassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sound_designer', 'サウンドデザイナー'), ('chief', 'チーフ')], max_length=30, verbose_name='役割')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='担当開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='担当終了日')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='productions.production', verbose_name='公演')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_memberships', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
            options={
                'verbose_name': '公演担当者',
                'verbose_name_plural': '公演担当者一覧',
                'ordering': ['start_date'],
            },
        ),
    ]
