# Generated by Django 5.2.12 on 2026-03-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0016_seed_process_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processday',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='実施日'),
        ),
    ]
