# Generated by Django 5.2.12 on 2026-03-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0019_seed_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequest',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='配車日'),
        ),
        migrations.AlterField(
            model_name='process',
            name='title',
            field=models.CharField(help_text='例: 稽古場仕込み、劇場仕込み', max_length=100, verbose_name='ブロック名'),
        ),
    ]
