# Generated by Django 5.2.12 on 2026-03-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0022_vehiclerequest_include_self_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='processday',
            name='setup_label',
            field=models.CharField(blank=True, choices=[('setup_staff', '仕込み人数'), ('stage_rehearsal', '舞台稽古'), ('opening_night', '初日')], default='', max_length=20, verbose_name='劇場仕込みラベル'),
        ),
    ]
