# Generated by Django 5.2.12 on 2026-03-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0027_process_request_unit_type_and_remove_process_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleassignment',
            options={'ordering': ['vehicle_request__process_request_unit__work_date', 'vehicle_request__requested_time'], 'verbose_name': '車両手配', 'verbose_name_plural': '車両手配一覧'},
        ),
        migrations.RenameIndex(
            model_name='processrequestunit',
            new_name='productions_process_16d59b_idx',
            old_name='productions_process_6e2bc1_idx',
        ),
        migrations.RenameIndex(
            model_name='processrequestunit',
            new_name='productions_process_028573_idx',
            old_name='productions_process_2fb720_idx',
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='arranged_time',
            field=models.TimeField(blank=True, null=True, verbose_name='手配時間'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='is_manager_added',
            field=models.BooleanField(default=False, verbose_name='管理側追加便'),
        ),
        migrations.AlterField(
            model_name='processday',
            name='setup_label',
            field=models.CharField(blank=True, choices=[('setup_staff', '仕込み'), ('stage_rehearsal', '舞台稽古'), ('opening_night', '初日')], default='', max_length=20, verbose_name='劇場仕込みラベル'),
        ),
        migrations.AlterField(
            model_name='processrequestunit',
            name='setup_label',
            field=models.CharField(blank=True, choices=[('setup_staff', '仕込み'), ('stage_rehearsal', '舞台稽古'), ('opening_night', '初日')], default='', max_length=20, verbose_name='劇場仕込みラベル'),
        ),
    ]
