# Generated by Django 5.2.12 on 2026-03-17 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('productions', '0030_vehicleassignment_departure_arrival_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequest',
            name='location_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='locations.location', verbose_name='出発地（マスタ）'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='location_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='locations.location', verbose_name='目的地（マスタ）'),
        ),
    ]
