# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="shin_on_db_id",
            field=models.IntegerField(
                blank=True,
                help_text="shin-on_db からの同期元ID（手動登録レコードは空）",
                null=True,
                unique=True,
                verbose_name="shin-on_db ID",
            ),
        ),
    ]
