# Generated by Django 5.2.12 on 2026-03-04 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_role', models.CharField(choices=[('admin', '管理者'), ('editor', '編集者'), ('general', '一般'), ('viewer', '閲覧者')], default='general', max_length=20, verbose_name='システムロール')),
                ('portal_uuid', models.CharField(blank=True, db_index=True, help_text='shin•on Portal の portal_uuid（不変ID）。JWT 連携時に自動設定される。', max_length=100, null=True, unique=True, verbose_name='ポータルUUID')),
                ('family_name', models.CharField(blank=True, default='', max_length=100, verbose_name='姓')),
                ('given_name', models.CharField(blank=True, default='', max_length=100, verbose_name='名')),
                ('phonetic_family_name', models.CharField(blank=True, default='', max_length=100, verbose_name='姓(ふりがな)')),
                ('phonetic_given_name', models.CharField(blank=True, default='', max_length=100, verbose_name='名(ふりがな)')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='メールアドレス')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
            },
        ),
    ]
