# Generated by Django 5.2.12 on 2026-03-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['order', 'family_name', 'given_name'], 'verbose_name': 'ユーザープロフィール', 'verbose_name_plural': 'ユーザープロフィール'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
    ]
