# Generated by Django 5.2.12 on 2026-03-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_userprofile_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='スタッフ一覧に表示'),
        ),
    ]
