# Generated by Django 5.2.12 on 2026-03-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['order', 'phonetic_family_name'], 'verbose_name': 'ユーザープロフィール', 'verbose_name_plural': 'ユーザープロフィール'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active_staff',
            field=models.BooleanField(default=True, verbose_name='担当者選択に表示'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='portal_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='ポータルUUID'),
        ),
    ]
