# Generated by Django 5.2.12 on 2026-03-04 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='車輌名')),
                ('vehicle_type', models.CharField(choices=[('2t', '2tトラック'), ('2tL', '2tロングトラック'), ('4t', '4tトラック'), ('car', '乗用車'), ('other', 'その他')], max_length=20, verbose_name='車種')),
                ('ownership_type', models.CharField(choices=[('company', '自社'), ('personal', '自家用'), ('external', '外注')], max_length=20, verbose_name='所有区分')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
            ],
            options={
                'verbose_name': '車輌',
                'verbose_name_plural': '車輌マスタ',
                'ordering': ['vehicle_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公演タイトル')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('description', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performances', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '公演',
                'verbose_name_plural': '公演一覧',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformancePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ポジション名')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='performances.performance', verbose_name='公演')),
            ],
            options={
                'verbose_name': 'ポジション',
                'verbose_name_plural': 'ポジション一覧',
            },
        ),
        migrations.CreateModel(
            name='PerformanceFreelanceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.PositiveIntegerField(verbose_name='単価（円）')),
                ('allowance', models.PositiveIntegerField(default=0, verbose_name='手当（円）')),
                ('valid_from', models.DateField(verbose_name='適用開始日')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='適用終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_rates', to='performances.performance', verbose_name='公演')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_rates', to=settings.AUTH_USER_MODEL, verbose_name='スタッフ')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_rates', to='performances.performanceposition', verbose_name='ポジション')),
            ],
            options={
                'verbose_name': 'フリーランス単価',
                'verbose_name_plural': 'フリーランス単価一覧',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工程名')),
                ('order', models.PositiveIntegerField(verbose_name='順序')),
                ('suggested_date', models.DateField(blank=True, null=True, verbose_name='予定日（目安）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='performances.performance', verbose_name='公演')),
            ],
            options={
                'verbose_name': '工程',
                'verbose_name_plural': '工程一覧',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PhaseSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_staff_count', models.PositiveIntegerField(default=0, verbose_name='希望人数')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('assigned', '割当済'), ('locked', '確定')], default='draft', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='performances.phase', verbose_name='工程')),
            ],
            options={
                'verbose_name': '人員枠',
                'verbose_name_plural': '人員枠一覧',
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied_start', models.DateTimeField(verbose_name='占有開始（集合）')),
                ('occupied_end', models.DateTimeField(verbose_name='占有終了（解散）')),
                ('applied_unit_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='確定単価（円）')),
                ('applied_allowance_total', models.PositiveIntegerField(default=0, verbose_name='確定手当合計（円）')),
                ('applied_total_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='確定合計金額（円）')),
                ('applied_position_name', models.CharField(blank=True, max_length=100, verbose_name='確定ポジション名')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='確定日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phase_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='performances.phaseslot', verbose_name='人員枠')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments', to='performances.performanceposition', verbose_name='ポジション')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL, verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '人員割当',
                'verbose_name_plural': '人員割当一覧',
            },
        ),
        migrations.CreateModel(
            name='VehicleOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='運行タイトル')),
                ('requested_start', models.DateTimeField(verbose_name='希望開始')),
                ('requested_end', models.DateTimeField(verbose_name='希望終了')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='確定開始')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='確定終了')),
                ('route_from', models.CharField(max_length=200, verbose_name='出発地')),
                ('route_to', models.CharField(max_length=200, verbose_name='到着地')),
                ('description', models.TextField(blank=True, default='', verbose_name='内容説明')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('assigned', '割当済'), ('locked', '確定')], default='draft', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_operations', to='performances.performance', verbose_name='公演')),
            ],
            options={
                'verbose_name': '運行工程',
                'verbose_name_plural': '運行工程一覧',
                'ordering': ['requested_start'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_external_driver', models.BooleanField(default=False, verbose_name='外注ドライバー')),
                ('applied_cost_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='外注費・ドライバー費（確定）')),
                ('applied_sales_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='案件請求額（確定）')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='確定日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_assignments', to=settings.AUTH_USER_MODEL, verbose_name='ドライバー')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='performances.vehicle', verbose_name='車輌')),
                ('vehicle_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='performances.vehicleoperation', verbose_name='運行工程')),
            ],
            options={
                'verbose_name': '配車割当',
                'verbose_name_plural': '配車割当一覧',
            },
        ),
    ]
