# Generated by Django 5.2.12 on 2026-03-05 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-created_at'], 'verbose_name': '公演', 'verbose_name_plural': '公演一覧'},
        ),
        migrations.AlterModelOptions(
            name='performanceposition',
            options={'ordering': ['order', 'name'], 'verbose_name': 'ポジションマスタ', 'verbose_name_plural': 'ポジションマスタ一覧'},
        ),
        migrations.RemoveField(
            model_name='performance',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='performanceposition',
            name='performance',
        ),
        migrations.AddField(
            model_name='performanceposition',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='title',
            field=models.CharField(max_length=200, verbose_name='公演名'),
        ),
        migrations.AlterField(
            model_name='performanceposition',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ポジション名'),
        ),
        migrations.CreateModel(
            name='PerformanceResponsibleStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_staff', to='performances.performance', verbose_name='公演')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_staff', to='performances.performanceposition', verbose_name='ポジション')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_performances', to=settings.AUTH_USER_MODEL, verbose_name='担当者（氏名）')),
            ],
            options={
                'verbose_name': '公演担当者',
                'verbose_name_plural': '公演担当者一覧',
                'unique_together': {('performance', 'user', 'position')},
            },
        ),
    ]
