# Generated by Django 5.2.12 on 2026-03-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_alter_performance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='suggested_time',
            field=models.TimeField(blank=True, null=True, verbose_name='予定時間（目安）'),
        ),
    ]
