# Generated by Django 5.2.12 on 2026-03-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0003_phase_suggested_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='suggested_time',
        ),
        migrations.AddField(
            model_name='phase',
            name='suggested_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了予定時間（目安）'),
        ),
        migrations.AddField(
            model_name='phase',
            name='suggested_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始予定時間（目安）'),
        ),
    ]
