# Generated by Django 5.2.12 on 2026-03-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0004_remove_phase_suggested_time_phase_suggested_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='suggested_date',
        ),
        migrations.AddField(
            model_name='phase',
            name='suggested_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了予定日（目安）'),
        ),
        migrations.AddField(
            model_name='phase',
            name='suggested_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始予定日（目安）'),
        ),
    ]
