# Generated by Django 5.2.12 on 2026-03-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0005_remove_phase_suggested_date_phase_suggested_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='備考'),
        ),
    ]
