# Generated by Django 5.2.12 on 2026-03-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0006_phase_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='工程名')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': '工程マスタ',
                'verbose_name_plural': '工程マスタ一覧',
                'ordering': ['order', 'name'],
            },
        ),
    ]
