# Generated by Django 5.2.12 on 2026-03-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0007_phasemaster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['order', 'name'], 'verbose_name': '車輌', 'verbose_name_plural': '車輌マスタ'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
    ]
