# Generated by Django 5.2.12 on 2026-03-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0008_alter_vehicle_options_vehicle_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('2t', '2tトラック'), ('2tL', '2tロングトラック'), ('4t', '4tトラック'), ('hiace', 'ハイエース'), ('keiban', '軽バン'), ('car', '乗用車'), ('other', 'その他')], max_length=20, verbose_name='車種'),
        ),
    ]
