# Generated by Django 5.2.12 on 2026-03-06 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0010_alter_vehicle_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleoperation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
        ),
        migrations.AddField(
            model_name='vehicleoperation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_vehicle_operations', to=settings.AUTH_USER_MODEL, verbose_name='削除実行者'),
        ),
        migrations.AddField(
            model_name='vehicleoperation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
    ]
