# Generated by Django 5.2.12 on 2026-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0012_vehicleoperation_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleoperation',
            name='requested_staff_count',
            field=models.PositiveIntegerField(default=0, verbose_name='希望助手人数'),
        ),
    ]
